#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const EXCLUDE_FILES = new Set(['_sidebar.md', '_navbar.md', '.nojekyll']);
const EXCLUDE_DIRS = new Set(['.git', '.github', 'scripts', 'node_modules']);

function getTitle(filepath) {
  try {
    const content = fs.readFileSync(filepath, 'utf-8');
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (trimmed.startsWith('# ')) {
        return trimmed.slice(2).trim();
      }
    }
  } catch (e) {}
  return path.basename(filepath, path.extname(filepath));
}

function scanDir(dir, base, indent = 0) {
  const lines = [];
  let entries;
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (e) {
    return lines;
  }

  entries.sort((a, b) => {
    if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
    return a.name.toLowerCase().localeCompare(b.name.toLowerCase());
  });

  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name.startsWith('_')) continue;

    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      const subLines = scanDir(path.join(dir, entry.name), base, indent + 1);
      if (subLines.length > 0) {
        lines.push(`${'  '.repeat(indent)}- **${entry.name}**`);
        lines.push(...subLines);
      }
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      if (EXCLUDE_FILES.has(entry.name)) continue;
      const filepath = path.join(dir, entry.name);
      const title = getTitle(filepath);
      const relPath = path.relative(base, filepath).replace(/\\/g, '/');

      if (entry.name === 'README.md') {
        const dirPath = path.relative(base, dir).replace(/\\/g, '/');
        if (dirPath === '.') continue;
        lines.unshift(`${'  '.repeat(indent)}- [${title}](${dirPath}/)`);
      } else {
        lines.push(`${'  '.repeat(indent)}- [${title}](${relPath})`);
      }
    }
  }
  return lines;
}

const base = process.cwd();
const output = [
  '<!-- Auto-generated by GitHub Actions — do not edit manually -->',
  '- [Home](/)',
  '',
  ...scanDir(base, base, 0),
];
console.log(output.join('\n'));
